config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :warehouses, only: %i[show new create edit update destroy]
  resources :suppliers, only: %i[index show new create edit update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  validates :brand_name, :corporate_name, :registration_number, :full_address, :city, :state, :email, presence: true
  validates :registration_number, uniqueness: true
end

app/models/warehouse.rb
class Warehouse < ApplicationRecord
  validates :name, :code, :city, :description, :address, :cep, :area, presence: true
  validates :code, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @warehouses = Warehouse.all
  end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :set_supplier, only: %i[show edit update]
  def index
    @suppliers = Supplier.all
  end

  def show
  end

  def new
    @supplier = Supplier.new
  end

  def create
    @supplier = Supplier.new(supplier_params)
    if @supplier.save
      redirect_to @supplier, notice: 'Fornecedor cadastrado com sucesso'
    else
      @supplier_errors = @supplier.errors.full_messages
      flash.now[:alert] = 'Erro ao cadastrar Fornecedor'
      render :new
    end
  end

  def edit
  end

  def update
    if @supplier.update(supplier_params)
      redirect_to @supplier, notice: 'Fornecedor atualizado com sucesso'
    else
    end
  end
  
  private

  def supplier_params
    params.require(:supplier).permit(:brand_name, :corporate_name, :registration_number, :full_address, :city, :state,
                                     :email)
  end

  def set_supplier
    @supplier = Supplier.find(params[:id])
  end
end

app/controllers/warehouses_controller.rb
class WarehousesController < ApplicationController
  before_action :set_warehouse, only: %i[show edit update destroy]

  def show
    @warehouse = Warehouse.find(params[:id])
  end

  def new
    @warehouse = Warehouse.new
  end

  def create
    @warehouse = Warehouse.new(warehouse_params)
    if @warehouse.save
      redirect_to @warehouse, notice: 'Galpão cadastrado com sucesso'
    else
      @warehouse_errors = @warehouse.errors.full_messages
      flash.now[:notice] = 'Erro ao cadastrar Galpão'
      render :new
    end
  end

  def edit
    @warehouse = Warehouse.find(params[:id])
  end

  def update
    if @warehouse.update(warehouse_params)
      redirect_to @warehouse, notice: 'Galpão atualizado com sucesso'
    else
      @warehouse_errors = @warehouse.errors.full_messages
      flash.now[:alert] = 'Erro ao atualizar Galpão'
      render :edit
    end
  end

  def destroy
    @warehouse.destroy
    redirect_to root_path, notice: 'Galpão excluído com sucesso'
  end

  private

  def warehouse_params
    params.require(:warehouse).permit(:name, :code, :city, :area, :address, :cep, :description)
  end

  def set_warehouse
    @warehouse = Warehouse.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<section id='warehouse'>
  <h2>Galpões</h2>

  <div>
    <%= link_to 'Cadastrar Galpão', new_warehouse_path %>
  </div>

  <% @warehouses.each do |warehouse| %>
    <h3><%= link_to warehouse.name, warehouse %></h3>
    <dl>
      <dt>Código:</dt>
      <dd><%= warehouse.code %></dd>

      <dt>Cidade:</dt>
      <dd><%= warehouse.city %></dd>

      <dt>Área:</dt>
      <dd><%= warehouse.area %> m²</dd>
    </dl>
  <% end %>


  <% if @warehouses.empty? %>
    <p>Não existem galpões cadastrados.</p>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WarehouseTemp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <header>

      <%= link_to root_path do %>
        <h1>Galpões & Estoque</h1>  
      <% end %>

      <nav>
        <%= link_to 'Fornecedores', suppliers_path %>
      </nav>

    </header>
    <main>

      <%= notice %>
      <%= alert %>
      <%= yield %>
      
    </main>
  </body>
</html>

app/views/suppliers/_form.html.erb
<%= form_with model: @supplier do |f| %>
  <div>
    <%= f.label :brand_name %>
    <%= f.text_field :brand_name %>
  </div>

  <div>
    <%= f.label :corporate_name %>
    <%= f.text_field :corporate_name %>
  </div>

  <div>
    <%= f.label :registration_number %>
    <%= f.text_field :registration_number %>
  </div>

  <div>
    <%= f.label :full_address %>
    <%= f.text_field :full_address %>
  </div>

  <div>
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div>
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/suppliers/edit.html.erb
<%= render 'form' %>

app/views/suppliers/index.html.erb
<div>
  <p><%= link_to 'Cadastrar Fornecedor', new_supplier_path %></p>
</div>

<table>
  <thead>

    <tr>
      <th>Nome</th>
      <th>Localização</th>
    </tr>

  </thead>

  <tbody>
    <% @suppliers.each do |supplier| %>

      <tr>
        <td><%= link_to supplier.brand_name, supplier %></td>
        <td><%= supplier.city %> - <%= supplier.state %></td>
      </tr>

    <% end %>
  </tbody>
</table>

<% if @suppliers.empty? %>
  <p>Nenhum fornecedor cadastrado</p>
<% end %>

app/views/suppliers/new.html.erb
<p><%= link_to 'Voltar para Fornecedores', suppliers_path %></p>

<% if @supplier_errors.present? %>
  <p>Atente-se aos erros abaixo:</p>

  <ul>
    <% @supplier_errors.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>

<% end %>

<%= render 'form' %>

app/views/suppliers/show.html.erb
<p><%= link_to "Editar #{@supplier.brand_name}", edit_supplier_path(@supplier) %></p>

<h2>Fornecedor <%= @supplier.brand_name %></h2>
<h2><%= @supplier.corporate_name %></h2>

<dl>
  <div>
    <dt>CNPJ:</dt>
    <dd><%= @supplier.registration_number %></dd>
  </div>

  <div>
    <dt>Endereço:</dt>
    <dd><%= @supplier.full_address %> - <%= @supplier.city %> - <%= @supplier.state %></dd>
  </div>

  <div>
    <dt>E-mail:</dt>
    <dd><%= @supplier.email %></dd>
  </div>
</dl>

app/views/warehouses/_form.html.erb
<%= form_with model: @warehouse do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :code %>
    <%= f.text_field :code %>
  </div>

  <div>
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div>
    <%= f.label :area %>
    <%= f.text_field :area %>
  </div>

  <div>
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div>
    <%= f.label :cep %>
    <%= f.text_field :cep %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/warehouses/edit.html.erb
<h2>Editar <%= @warehouse.name %></h2>

<div>

  <%= link_to @warehouse do %>
    Voltar para <%= @warehouse.name %>
  <% end %>
  
</div>

<% if @warehouse_errors.present? %>
  <p>Atente-se aos erros abaixo:</p>

  <ul>
    <% @warehouse_errors.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>

<% end %>

<%= render 'form' %>

app/views/warehouses/new.html.erb
<h1>Criar Galpão</h1>

<% if @warehouse_errors.present? %>
  <p>Atente-se aos erros abaixo:</p>

  <ul>
    <% @warehouse_errors.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>

<% end %>

<%= render 'form' %>

app/views/warehouses/show.html.erb
<h1>Galpão <%= @warehouse.code %></h1>
<h2><%= @warehouse.description %></h2>

<div>
  <%= link_to 'Editar Galpão', edit_warehouse_path(@warehouse) %> | 
  <%= button_to 'Deletar Galpão', @warehouse, method: :delete, onclick: "return confirm('Você tem certeza que deseja excluir o Galpão?');" %>
</div>

<div>
  <dl>
    <div>
      <dt>Nome: </dt>
      <dd><%= @warehouse.name %></dd>
    </div>

    <div>
      <dt>Cidade: </dt>
      <dd><%= @warehouse.city %></dd>
    </div>

    <div>
      <dt>Área: </dt>
      <dd><%= @warehouse.area %> m²</dd>
    </div>

    <div>
      <dt>Endereço: </dt>
      <dd><%= @warehouse.address %> CEP: <%= @warehouse.cep %></dd>
    </div>
  </dl>
</div>